server:
  port: 9000
spring:
  application:
    name: nacos-order-consume
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.111.130:8848 # nacos地址

service-url:
  nacos-user-service: http://nacos-pay-provider

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
