server:
  port: 8000

spring:
  application:
    name: cloud-consumer-openfeign-order
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        prefer-agent-address: true
    openfeign:
      client:
        config:
          default:
            #连接超时时间ms
            connect-timeout: 20000
            #业务处理超时时间ms
            read-timeout: 20000
          #更加精细的超时控制，优先这个生效
          cloud-payment-service:
            connect-timeout: 30000
            read-timeout: 30000
      #apache httpclient5 配置开启
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json #触发压缩数据类型
          min-request-size: 2048 #触发压缩最小的size
        response:
          enabled: true
      circuitbreaker:
        enabled: true
        group:
          enabled: true

#feign日志以什么级别监控哪个接口
logging:
  level:
    com:
      wsj:
        cloud:
          apis:
            PayFeignApi: debug

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0 # 采样率,默认值0.1(就是10%的链路会被记录下来)

resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 2 # 一次刷新周期内允许最大的请求数
        limit-refresh-period: 1s # 刷新周期
        timeout-duration: 1 # 默认等待时间
    instances:
      cloud-payment-service:
        base-config: default

# 基于次数的降级
#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s # 默认1s 超过1s直接降级 (坑)
#    #  thread-pool-bulkhead: # 线程池
#    #    configs:
#    #      default:
#    #        max-thread-pool-size: 1
#    #        core-thread-pool-size: 1
#    #        queue-capacity: 1
#    #    instances:
#    #      cloud-payment-service:
#    #        base-config: default
#  circuitbreaker: # 降级熔断
#    configs:
#      default:
#        failure-rate-threshold: 50 # 调用失败达到50%后打开断路器
#        sliding-window-type: count_based # 滑动窗口类型
#        sliding-window-size: 6 # 滑动窗口大小 count_based6个请求 time_base6秒
#        minimum-number-of-calls: 6 # 每个滑动窗口的周期
#        automatic-transition-from-open-to-half-open-enabled: true # 开始过度到半开状态
#        wait-duration-in-open-state: 5s # 从开启到半开启需要5s
#        permitted-number-of-calls-in-half-open-state: 2 #半开状态允许通过的最大请求数
#        record-exceptions:
#          - java.lang.Exception
#    instances:
#      cloud-payment-service:
#        base-config: default
#  bulkhead: # 信号量舱壁
#    configs:
#      default:
#        max-concurrent-calls: 2 #隔离允许线程最大数量
#        max-wait-duration: 1s #1s后，过期不候
#    instances:
#      cloud-payment-service:
#        base-config: default



# 基于慢调用的降级
#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s # 默认1s 超过1s直接降级 (坑)
#  circuitbreaker:
#    configs:
#      default:
#        failure-rate-threshold: 50 # 调用失败达到50%后打开断路器
#        slow-call-duration-threshold: 2s # 慢调用时间阈值
#        slow-call-rate-threshold: 30 # 慢调用百分比峰值
#        sliding-window-type: time_based # 滑动窗口类型
#        sliding-window-size: 2 # 滑动窗口大小 count_based6个请求 time_base6秒
#        minimum-number-of-calls: 2 # 每个滑动窗口的周期
#        automatic-transition-from-open-to-half-open-enabled: true # 开始过度到半开状态
#        wait-duration-in-open-state: 5s # 从开启到半开启需要5s
#        permitted-number-of-calls-in-half-open-state: 2 #半开状态允许通过的最大请求数
#        record-exceptions:
#          - java.lang.Exception
#    instances:
#      cloud-payment-service:
#        base-config: default


#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s # 默认1s 超过1s直接降级 (坑)
#  thread-pool-bulkhead: # 线程池
#    configs:
#      default:
#          max-thread-pool-size: 1
#          core-thread-pool-size: 1
#          queue-capacity: 1
#    instances:
#      cloud-payment-service:
#        base-config: default